services:
  - type: web
    name: incluscore-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ENV
        value: production
    autoDeploy: true
